import { ReactComponent as Tire } from "assets/images/recommand/tires/kh_hp71.svg"

const Tires = [
    {
        id: 1,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 2,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 3,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 4,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 5,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 6,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 7,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 8,
        image: <Tire/>,
        brand: "금호",
        name: "크루젠 HP71",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
]

export { Tires }